#!/bin/bash

rsync -au --delete "/home/aki/.local/share/backgrounds/" "/mnt/home/linux_setup/" #copy recursively, but only if doesnt exist on target or target version is older, delete things i deleted
