name: Shellcheck

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install shellcheck
        run: sudo apt update && sudo apt install -y shellcheck

      - name: Run shellcheck
        run: |
          shellcheck -V
          shellcheck -a start.sh src/*/*.sh --shell=bash
